### ISSUE TITLE
Review Indexed Fields for Libguides Database Assets

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_api#219]
### Expected behavior
A query of "academic" brings back only 3 results now. Guides internal search produces 77 results. 

### Actual behavior
Include screenshots, or links and browser version if relevant

### Steps to replicate

- [x] Review and confirm fields that we are indexing

### Implementation notes, if any

Check our database query: does it only request 3 results?

**Comment by sandbergja** [comment]
As @maxkadel pointed out earlier today, the number "3" is just because we were limiting to 3 results.  When we remove the limit, there are 57 results for "academic", which still differs from the 77 that libguides returns.

I confirmed that the following fields are indexed for searching:

- name
- description
- alt_names
- subjects
